/*
-- Query: SELECT * FROM ECommerce.supplier
LIMIT 0, 1000

-- Date: 2022-03-20 11:17
*/
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (1,'Anchor Computer Inc','973-767-3008','erinn.canlas@canlas.com','13 S Hacienda Dr','Livingston','NJ','Essex','7039');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (2,'Sebring & Co','248-980-6904','cherry@lietz.com','40 9th Ave Sw #91','Waterford','MI','Oakland','48329');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (3,'H A C Farm Lines Co Optv Assoc','216-923-3715','kattie@vonasek.org','2845 Boulder Crescent St','Cleveland','OH','Cuyahoga','44103');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (4,'Hunter, John J Esq','325-631-1560','lilli@aol.com','33 State St','Abilene','TX','Taylor','79601');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (5,'Freehold Fence Co','817-526-4408','whitley.tomasulo@aol.com','2 S 15th St','Fort Worth','TX','Tarrant','76107');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (6,'Binswanger','718-201-3751','badkin@hotmail.com','4 Kohler Memorial Dr','Brooklyn','NY','Kings','11230');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (7,'Chilton Malting Co','401-893-4882','hermila_thyberg@hotmail.com','1 Rancho Del Mar Shopping C','Providence','RI','Providence','2903');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (8,'Schoen, Edward J Jr','717-885-9118','jesusita.flister@hotmail.com','3943 N Highland Ave','Lancaster','PA','Lancaster','17601');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (9,'Helderman, Seymour Cpa','401-948-4982','caitlin.julia@julia.org','5 Williams St','Johnston','RI','Providence','2919');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (10,'Denbrook, Myron','305-622-4739','roosevelt.hoffis@aol.com','60 Old Dover Rd','Hialeah','FL','Miami-Dade','33014');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (11,'Lippitt, Mike','201-832-4168','hhalter@yahoo.com','8 Sheridan Rd','Jersey City','NJ','Hudson','7304');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (12,'Hiram, Hogg P Esq','210-856-4979','lorean.martabano@hotmail.com','85092 Southern Blvd','San Antonio','TX','Bexar','78204');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (13,'In Travel Agency','718-478-8504','france.buzick@yahoo.com','64 Newman Springs Rd E','Brooklyn','NY','Kings','11219');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (14,'Newhart Foods Inc','909-993-3242','jferrario@hotmail.com','48 Stratford Ave','Pomona','CA','Los Angeles','91768');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (15,'Courtyard By Marriott','216-230-4892','adelina_nabours@gmail.com','80 Pittsford Victor Rd #9','Cleveland','OH','Cuyahoga','44103');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (16,'Studer, Eugene A Esq','212-304-4515','ddhamer@cox.net','87163 N Main Ave','New York','NY','New York','10013');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (17,'Seashore Supply Co Waretown','804-762-9576','jerry.dallen@yahoo.com','393 Lafayette Ave','Richmond','VA','Richmond City','23219');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (18,'Mayar Silk Inc','706-221-4243','leota.ragel@gmail.com','99 5th Ave #33','Trion','GA','Chattooga','30753');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (19,'National Medical Excess Corp','337-515-1438','jamyot@hotmail.com','49 N Mays St','Broussard','LA','Lafayette','70518');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (20,'Stero Company','973-544-2677','aja_gehrett@hotmail.com','993 Washington Ave','Nutley','NJ','Essex','7110');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (21,'Hasting, H Duane Esq','607-407-3716','kirk.herritt@aol.com','88 15th Ave Ne','Vestal','NY','Broome','13850');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (22,'Insty Prints','973-412-2995','leonora@yahoo.com','3381 E 40th Ave','Passaic','NJ','Passaic','7055');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (23,'Glenridge Manor Mobile Home Pk','208-252-4552','winfred_brucato@hotmail.com','201 Ridgewood Rd','Moscow','ID','Latah','83843');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (24,'Circuit Solution Inc','415-411-1775','tarra.nachor@cox.net','39 Moccasin Dr','San Francisco','CA','San Francisco','94104');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (25,'Local Office','508-942-4186','corinne@loder.org','4 Carroll St','North Attleboro','MA','Bristol','2760');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (26,'Lee Kilkelly Paulson & Kabaker','248-357-8718','dulce_labreche@yahoo.com','9581 E Arapahoe Rd','Rochester','MI','Oakland','48307');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (27,'Davis, Maxon R Esq','920-353-6377','kate_keneipp@yahoo.com','33 N Michigan Ave','Green Bay','WI','Brown','54301');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (28,'Garrison, Paul E Esq','410-665-4903','kaitlyn.ogg@gmail.com','2 S Biscayne Blvd','Baltimore','MD','Baltimore City','21230');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (29,'Black History Resource Center','719-669-1664','sherita.saras@cox.net','8 Us Highway 22','Colorado Springs','CO','El Paso','80937');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (30,'Rodriguez, J Christopher Esq','419-588-8719','lstuer@cox.net','7422 Martin Ave #8','Toledo','OH','Lucas','43607');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (31,'Grant Family Health Center','301-998-9644','ernest@cox.net','94 Chase Rd','Hyattsville','MD','Prince Georges','20785');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (32,'Goeman Wood Products Inc','508-855-9887','nobuko.halsey@yahoo.com','8139 I Hwy 10 #92','New Bedford','MA','Bristol','2745');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (33,'Linhares, Kenneth A Esq','703-483-1970','lavonna.wolny@hotmail.com','5 Cabot Rd','Mc Lean','VA','Fairfax','22102');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (34,'Earnhardt Printing','410-678-2473','llizama@cox.net','3387 Ryan Dr','Hanover','MD','Anne Arundel','21076');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (35,'H P G Industrys Inc','512-223-4791','mariann.bilden@aol.com','3125 Packer Ave #9851','Austin','TX','Travis','78753');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (36,'Bailey Transportation Prod Inc','623-461-8551','helene@aol.com','347 Chestnut St','Peoria','AZ','Maricopa','85381');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (37,'Mcglynn Bliss Pc','419-571-5920','roselle.estell@hotmail.com','8116 Mount Vernon Ave','Bucyrus','OH','Crawford','44820');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (38,'Mutual Fish Co','206-311-4137','sheintzman@hotmail.com','8772 Old County Rd #5410','Kent','WA','King','98032');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (39,'Yeates, Arthur L Aia','513-617-2362','margart_meisel@yahoo.com','868 State St #38','Cincinnati','OH','Hamilton','45251');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (40,'Logan, Ronald J Esq','812-368-1511','kristofer.bennick@yahoo.com','772 W River Dr','Bloomington','IN','Monroe','47404');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (41,'Advantage Martgage Company','847-353-2156','wacuff@gmail.com','73 W Barstow Ave','Arlington Heights','IL','Cook','60004');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (42,'Germer And Gertz Llp','718-232-2337','shalon@cox.net','61047 Mayfield Ave','Brooklyn','NY','Kings','11223');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (43,'Spence Law Offices','407-446-4358','denise@patak.org','2139 Santa Rosa Ave','Orlando','FL','Orange','32801');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (44,'John Ortiz Nts Therapy Center','310-820-2117','louvenia.beech@beech.com','598 43rd St','Beverly Hills','CA','Los Angeles','90210');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (45,'Mike Uchrin Htg & Air Cond Inc','813-797-4816','audry.yaw@yaw.org','70295 Pioneer Ct','Brandon','FL','Hillsborough','33511');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (46,'Mccoy, Joy Reynolds Esq','915-452-1290','kristel.ehmann@aol.com','92899 Kalakaua Ave','El Paso','TX','El Paso','79925');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (47,'Kbor 1600 Am','619-603-5125','vzepp@gmail.com','395 S 6th St #2','El Cajon','CA','San Diego','92020');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (48,'Quality Inn Northwest','301-841-5012','egwalthney@yahoo.com','9506 Edgemore Ave','Bladensburg','MD','Prince Georges','20710');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (49,'Wallace Church Assoc Inc','714-523-6653','venita_maillard@gmail.com','72119 S Walker Ave #63','Anaheim','CA','Orange','92801');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (50,'Can Tron','314-732-9131','kasandra_semidey@semidey.com','369 Latham St #500','Saint Louis','MO','Saint Louis City','63102');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (51,'Ravaal Enterprises Inc','512-233-1831','xdiscipio@gmail.com','3158 Runamuck Pl','Round Rock','TX','Williamson','78664');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (52,'Thompson Steel Company Inc','336-670-2640','mlinahan@yahoo.com','9 Plainsboro Rd #598','Greensboro','NC','Guilford','27409');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (53,'Anderson, Mark A Esq','631-443-4710','krauser@cox.net','8728 S Broad St','Coram','NY','Suffolk','11727');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (54,'Womack & Galich','201-825-2514','pdubaldi@hotmail.com','2215 Prosperity Dr','Lyndhurst','NJ','Bergen','7071');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (55,'Valerie & Company','901-412-4381','linn_paa@paa.com','1 S Pine St','Memphis','TN','Shelby','38112');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (56,'Gehring Pumps Inc','404-505-4445','paris@hotmail.com','187 Market St','Atlanta','GA','Fulton','30342');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (57,'Haehnel, Craig W Esq','650-473-1262','wynell_dorshorst@dorshorst.org','94290 S Buchanan St','Pacifica','CA','San Mateo','94044');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (58,'Spoor Behrins Campbell & Young','952-702-7993','qbirkner@aol.com','7061 N 2nd St','Burnsville','MN','Dakota','55337');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (59,'Ken Jeter Store Equipment Inc','480-726-1280','regenia.kannady@cox.net','10759 Main St','Scottsdale','AZ','Maricopa','85260');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (60,'Potter, Brenda J Cpa','718-976-8610','sheron@aol.com','97 E 3rd St #9','Long Island City','NY','Queens','11101');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (61,'Baird Kurtz & Dobson','770-844-3447','izetta.funnell@hotmail.com','82 Winsor St #54','Atlanta','GA','Dekalb','30340');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (62,'Minor, Cynthia A Esq','507-210-3510','rodolfo@hotmail.com','41 Steel Ct','Northfield','MN','Rice','55057');
INSERT INTO `` (`supplierid`,`suppliername`,`suppliercontact`,`supplieremail`,`supplieraddress`,`suppliercity`,`supplierstate`,`suppliercountyy`,`supplierzipcode`) VALUES (63,'Solove, Robert A Esq','203-461-1949','zona@hotmail.com','49440 Dearborn St','Norwalk','CT','Fairfield','6854');
